CREATE TABLE `duplicate_groups` (
	`id` text PRIMARY KEY NOT NULL,
	`reasons` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `geocode_cache` (
	`address_key` text PRIMARY KEY NOT NULL,
	`latitude` real,
	`longitude` real,
	`precision` text DEFAULT 'unknown' NOT NULL,
	`provider` text NOT NULL,
	`formatted_address` text,
	`raw` text,
	`created_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `listing_events` (
	`id` text PRIMARY KEY NOT NULL,
	`listing_id` text NOT NULL,
	`source_run_id` text,
	`event_type` text NOT NULL,
	`old_value` text,
	`new_value` text,
	`note` text,
	`created_at` text NOT NULL,
	FOREIGN KEY (`listing_id`) REFERENCES `listings`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `listing_events_listing_idx` ON `listing_events` (`listing_id`,`created_at`);--> statement-breakpoint
CREATE TABLE `listings` (
	`id` text PRIMARY KEY NOT NULL,
	`source_id` text NOT NULL,
	`source_system` text NOT NULL,
	`source_listing_id` text NOT NULL,
	`original_url` text NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`raw_description` text,
	`property_name` text,
	`unit_number_public` text,
	`address_raw` text,
	`address_normalized` text,
	`neighborhood` text,
	`source_neighborhood_raw` text,
	`city` text,
	`state` text,
	`postal_code` text,
	`latitude` real,
	`longitude` real,
	`geocode_precision` text DEFAULT 'unknown' NOT NULL,
	`price_raw` text,
	`price_monthly` real,
	`price_effective_monthly` real,
	`concessions_raw` text,
	`deposit_raw` text,
	`deposit_amount` real,
	`bedrooms_raw` text,
	`bedrooms` real,
	`bathrooms_raw` text,
	`bathrooms` real,
	`square_feet_raw` text,
	`square_feet` integer,
	`price_per_square_foot` real,
	`property_type` text,
	`listing_type` text,
	`lease_term_raw` text,
	`lease_term_months` integer,
	`move_in_date` text,
	`available_date` text,
	`posted_date_raw` text,
	`posted_at` text,
	`first_seen_at` text NOT NULL,
	`last_seen_at` text NOT NULL,
	`missing_since` text,
	`detail_fetched_at` text,
	`stale_status` text DEFAULT 'active' NOT NULL,
	`listing_status` text DEFAULT 'active' NOT NULL,
	`photos` text,
	`primary_photo_url` text,
	`floor_plan_urls` text,
	`virtual_tour_url` text,
	`amenities_raw` text,
	`amenities_normalized` text,
	`laundry_raw` text,
	`laundry_normalized` text,
	`parking_raw` text,
	`parking_normalized` text,
	`pet_policy_raw` text,
	`cats_allowed` integer,
	`dogs_allowed` integer,
	`dog_restrictions_raw` text,
	`utilities_raw` text,
	`utilities_included` text,
	`application_fee_raw` text,
	`application_fee` real,
	`broker_fee_raw` text,
	`broker_fee` real,
	`contact_name` text,
	`contact_phone` text,
	`contact_email` text,
	`contact_url` text,
	`showing_info_raw` text,
	`application_url` text,
	`content_hash` text NOT NULL,
	`description_hash` text,
	`photo_hash` text,
	`duplicate_group_id` text,
	`scam_risk_level` text DEFAULT 'none' NOT NULL,
	`scam_warnings` text,
	`raw_payload` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`source_id`) REFERENCES `sources`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `listings_source_listing_unique` ON `listings` (`source_id`,`source_listing_id`);--> statement-breakpoint
CREATE INDEX `listings_stale_idx` ON `listings` (`source_id`,`stale_status`);--> statement-breakpoint
CREATE INDEX `listings_last_seen_idx` ON `listings` (`last_seen_at`);--> statement-breakpoint
CREATE TABLE `saved_searches` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`criteria` text NOT NULL,
	`enabled` integer DEFAULT true NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `source_runs` (
	`id` text PRIMARY KEY NOT NULL,
	`source_id` text NOT NULL,
	`started_at` text NOT NULL,
	`finished_at` text,
	`status` text DEFAULT 'failed' NOT NULL,
	`listings_found` integer DEFAULT 0 NOT NULL,
	`new_listings` integer DEFAULT 0 NOT NULL,
	`changed_listings` integer DEFAULT 0 NOT NULL,
	`price_changed_listings` integer DEFAULT 0 NOT NULL,
	`missing_listings` integer DEFAULT 0 NOT NULL,
	`suspected_duplicates` integer DEFAULT 0 NOT NULL,
	`suspected_scams` integer DEFAULT 0 NOT NULL,
	`pages_visited` integer DEFAULT 0 NOT NULL,
	`detail_pages_visited` integer DEFAULT 0 NOT NULL,
	`total_listings_reported_by_source` integer,
	`pagination_completed` integer,
	`detail_extraction_completed` integer,
	`stale_processed` integer DEFAULT false NOT NULL,
	`error_message` text,
	`warnings` text,
	`pagination_trace` text,
	`parser_version` integer,
	`html_hash` text,
	`raw_debug_path` text,
	`created_at` text NOT NULL,
	FOREIGN KEY (`source_id`) REFERENCES `sources`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE INDEX `source_runs_source_idx` ON `source_runs` (`source_id`,`started_at`);--> statement-breakpoint
CREATE TABLE `sources` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`source_system` text NOT NULL,
	`adapter_type` text NOT NULL,
	`priority` text DEFAULT 'normal' NOT NULL,
	`enabled` integer DEFAULT false NOT NULL,
	`listing_url` text,
	`base_url` text,
	`website_url` text,
	`contact_url` text,
	`phone` text,
	`email` text,
	`region` text,
	`city` text,
	`state` text,
	`crawl_interval_hours` integer DEFAULT 24 NOT NULL,
	`request_delay_ms` integer DEFAULT 2500 NOT NULL,
	`timeout_ms` integer DEFAULT 20000 NOT NULL,
	`retry_count` integer DEFAULT 2 NOT NULL,
	`max_pages_per_run` integer DEFAULT 10 NOT NULL,
	`max_detail_pages_per_run` integer DEFAULT 40 NOT NULL,
	`geocode_enabled` integer DEFAULT true NOT NULL,
	`needs_javascript` integer,
	`has_pagination` integer,
	`requires_detail_pages` integer,
	`blocks_automation` integer,
	`safe_for_personal_low_frequency_fetching` integer,
	`permission_status` text DEFAULT 'unknown' NOT NULL,
	`robots_status` text DEFAULT 'not_checked' NOT NULL,
	`robots_checked_at` text,
	`robots_notes` text,
	`source_status_notes` text,
	`notes` text,
	`parser_version` integer DEFAULT 1 NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `user_listing_states` (
	`listing_id` text PRIMARY KEY NOT NULL,
	`status` text NOT NULL,
	`note` text,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`listing_id`) REFERENCES `listings`(`id`) ON UPDATE no action ON DELETE no action
);
