import type { NewSourceRow } from "@/db/schema";

/**
 * SF source registry seed data. `npm run seed:sources` upserts these.
 *
 * Operational notes (robots/permission fields) were recorded from manual
 * checks on 2026-07-01 and are refreshed automatically at run time. They are
 * operational bookkeeping for a personal low-frequency tool — not legal
 * conclusions.
 *
 * Only sources with a registered adapterType ("craigslist", "rentsfnow",
 * "mock") can actually run; everything else is seeded disabled for future
 * investigation so the registry documents the roadmap.
 */

type SourceSeed = Omit<NewSourceRow, "createdAt" | "updatedAt">;

export const SOURCE_SEEDS: SourceSeed[] = [
  {
    id: "craigslist_sf",
    name: "Craigslist SF apartments",
    sourceSystem: "craigslist",
    adapterType: "craigslist",
    priority: "critical",
    registryStatus: "enabled_working",
    enabled: true,
    listingUrl: "https://sfbay.craigslist.org/search/sfc/apa",
    baseUrl: "https://sfbay.craigslist.org",
    websiteUrl: "https://sfbay.craigslist.org",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 2500,
    timeoutMs: 25000,
    retryCount: 2,
    maxPagesPerRun: 1,
    maxDetailPagesPerRun: 50,
    geocodeEnabled: true,
    needsJavaScript: false,
    hasPagination: false,
    requiresDetailPages: true,
    blocksAutomation: false,
    safeForPersonalLowFrequencyFetching: true,
    permissionStatus: "ok_personal_low_frequency",
    sourceStatusNotes:
      "Verified 2026-07-01: robots.txt disallows only /reply, /fb/, /suggest, /flag, /mf, /mailflag, /eaf — search and posting pages are not disallowed. Static search fallback serves ~360 newest results without JavaScript; offset pagination is ignored by the static page (JS-only), so each run sees the freshest ~360 SF postings. Detail pages are classic server-rendered HTML with coordinates, attributes, and photos.",
    notes:
      "Freshest small-landlord inventory in SF, but the noisiest: needs scam/duplicate handling. Fetch cautiously — daily or manual, never aggressive. Detail pages fetched only for new/changed postings.",
    parserVersion: 1,
  },
  {
    id: "rentsfnow",
    name: "RentSFNow",
    sourceSystem: "rentsfnow",
    adapterType: "rentsfnow",
    priority: "high",
    registryStatus: "enabled_working",
    enabled: true,
    listingUrl: "https://www.rentsfnow.com/search/",
    baseUrl: "https://www.rentsfnow.com",
    websiteUrl: "https://www.rentsfnow.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 2000,
    timeoutMs: 25000,
    retryCount: 2,
    maxPagesPerRun: 10,
    maxDetailPagesPerRun: 40,
    geocodeEnabled: true,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: true,
    blocksAutomation: false,
    safeForPersonalLowFrequencyFetching: true,
    permissionStatus: "ok_personal_low_frequency",
    sourceStatusNotes:
      "Verified 2026-07-01: WordPress site; its own search UI POSTs to /wp-admin/admin-ajax.php (action=wpas_ajax_load) and receives server-rendered result HTML with explicit current_page/last_page markers and building-level map coordinates. Unit detail pages are server-rendered. Also lists Oakland/LA inventory — adapter filters to San Francisco.",
    notes:
      "Property-manager direct inventory (large SF portfolio). Structured, well-paginated, and polite to fetch at low frequency.",
    parserVersion: 1,
  },
  {
    id: "mock_sf",
    name: "Mock SF data (dev)",
    sourceSystem: "mock",
    adapterType: "mock",
    priority: "normal",
    registryStatus: "disabled_reference_only",
    enabled: false,
    listingUrl: null,
    baseUrl: null,
    websiteUrl: null,
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 0,
    timeoutMs: 5000,
    retryCount: 0,
    maxPagesPerRun: 1,
    maxDetailPagesPerRun: 100,
    geocodeEnabled: false,
    needsJavaScript: false,
    hasPagination: false,
    requiresDetailPages: false,
    blocksAutomation: false,
    safeForPersonalLowFrequencyFetching: true,
    permissionStatus: "ok_personal_low_frequency",
    sourceStatusNotes: "Local development data; no network requests.",
    notes:
      "Realistic SF mock listings for UI work. Run via `npm run seed:mock` (uses APT_MOCK_PHASE to simulate price drops, disappearances, and new listings). Disabled so `ingest --all` doesn't mix mock data into real data.",
    parserVersion: 1,
  },
  {
    id: "zillow_sf",
    name: "Zillow SF rentals",
    sourceSystem: "zillow_manual_or_reference",
    adapterType: "none",
    priority: "reference_only",
    registryStatus: "disabled_reference_only",
    enabled: false,
    listingUrl: "https://www.zillow.com/san-francisco-ca/rentals/",
    baseUrl: "https://www.zillow.com",
    websiteUrl: "https://www.zillow.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 0,
    requestDelayMs: 5000,
    timeoutMs: 25000,
    retryCount: 0,
    maxPagesPerRun: 0,
    maxDetailPagesPerRun: 0,
    geocodeEnabled: false,
    needsJavaScript: true,
    hasPagination: true,
    requiresDetailPages: true,
    blocksAutomation: true,
    safeForPersonalLowFrequencyFetching: false,
    permissionStatus: "reference_only_do_not_fetch",
    sourceStatusNotes:
      "Reference only in phase one. Heavy JS app with strong anti-automation; not an appropriate foundation for a polite personal scraper. Use manually in a browser for cross-checking.",
    notes: "Seeded disabled by design. Revisit only with a clearly acceptable integration path.",
    parserVersion: 0,
  },
  {
    id: "apartments_com_sf",
    name: "Apartments.com SF rentals",
    sourceSystem: "apartments_manual_or_reference",
    adapterType: "none",
    priority: "reference_only",
    registryStatus: "disabled_reference_only",
    enabled: false,
    listingUrl: "https://www.apartments.com/san-francisco-ca/",
    baseUrl: "https://www.apartments.com",
    websiteUrl: "https://www.apartments.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 0,
    requestDelayMs: 5000,
    timeoutMs: 25000,
    retryCount: 0,
    maxPagesPerRun: 0,
    maxDetailPagesPerRun: 0,
    geocodeEnabled: false,
    needsJavaScript: true,
    hasPagination: true,
    requiresDetailPages: true,
    blocksAutomation: true,
    safeForPersonalLowFrequencyFetching: false,
    permissionStatus: "reference_only_do_not_fetch",
    sourceStatusNotes:
      "Reference only in phase one. Large marketplace with anti-automation; use manually in a browser for cross-checking.",
    notes: "Seeded disabled by design.",
    parserVersion: 0,
  },
  {
    id: "structure_properties",
    name: "Structure Properties",
    sourceSystem: "property_manager_direct",
    adapterType: "appfolio_js",
    priority: "normal",
    registryStatus: "disabled_needs_adapter",
    enabled: false,
    listingUrl: "https://structureproperties.appfolio.com/listings",
    baseUrl: "https://structureproperties.appfolio.com",
    websiteUrl: "https://www.structureproperties.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 1,
    maxPagesPerRun: 5,
    maxDetailPagesPerRun: 20,
    geocodeEnabled: true,
    needsJavaScript: true,
    hasPagination: true,
    requiresDetailPages: true,
    blocksAutomation: null,
    safeForPersonalLowFrequencyFetching: null,
    permissionStatus: "needs_review",
    sourceStatusNotes:
      "Checked 2026-07-01: AppFolio-hosted listings page reachable, but listing cards are rendered client-side and the widget's JSON endpoint (/listings/listings.json) returns 401 without the widget's own session context. Needs a Playwright-based adapter (adapterType appfolio_js, not yet implemented).",
    notes: "SF property manager on AppFolio. Good candidate for the first Playwright adapter — one adapter would cover every AppFolio PM.",
    parserVersion: 0,
  },
  {
    id: "gaetani_real_estate",
    name: "Gaetani Real Estate",
    sourceSystem: "property_manager_direct",
    adapterType: "appfolio_js",
    priority: "normal",
    registryStatus: "disabled_needs_adapter",
    enabled: false,
    listingUrl: "https://gaetani.appfolio.com/listings",
    baseUrl: "https://gaetani.appfolio.com",
    websiteUrl: "https://www.gaetanirealestate.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 1,
    maxPagesPerRun: 5,
    maxDetailPagesPerRun: 20,
    geocodeEnabled: true,
    needsJavaScript: true,
    hasPagination: true,
    requiresDetailPages: true,
    blocksAutomation: null,
    safeForPersonalLowFrequencyFetching: null,
    permissionStatus: "needs_review",
    sourceStatusNotes:
      "Checked 2026-07-01: AppFolio-hosted listings page reachable; same JS-rendered widget as Structure Properties. Shares the future appfolio_js adapter.",
    notes: "Long-standing SF property manager on AppFolio.",
    parserVersion: 0,
  },
  {
    id: "trinity_sf",
    name: "Trinity SF",
    sourceSystem: "property_manager_direct",
    adapterType: "none",
    priority: "normal",
    registryStatus: "disabled_needs_review",
    enabled: false,
    listingUrl: "https://www.trinitysf.com",
    baseUrl: "https://www.trinitysf.com",
    websiteUrl: "https://www.trinitysf.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 1,
    maxPagesPerRun: 5,
    maxDetailPagesPerRun: 20,
    geocodeEnabled: true,
    needsJavaScript: null,
    hasPagination: null,
    requiresDetailPages: null,
    blocksAutomation: null,
    safeForPersonalLowFrequencyFetching: null,
    permissionStatus: "needs_review",
    sourceStatusNotes:
      "Checked 2026-07-02: homepage reachable (WordPress) but its own /san-francisco-apartments/ link returns 404 — no availability/listing page identified yet. Needs review to locate the real availability page before an adapter is possible.",
    notes: "Large SF landlord (thousands of units). Availability page structure TBD.",
    parserVersion: 0,
  },
  {
    id: "mosser_living",
    name: "Mosser Living",
    sourceSystem: "property_manager_direct",
    adapterType: "none",
    priority: "normal",
    registryStatus: "disabled_needs_adapter",
    enabled: false,
    listingUrl: "https://www.mosserliving.com",
    baseUrl: "https://www.mosserliving.com",
    websiteUrl: "https://www.mosserliving.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 1,
    maxPagesPerRun: 5,
    maxDetailPagesPerRun: 20,
    geocodeEnabled: true,
    needsJavaScript: null,
    hasPagination: null,
    requiresDetailPages: null,
    blocksAutomation: null,
    safeForPersonalLowFrequencyFetching: null,
    permissionStatus: "needs_review",
    sourceStatusNotes:
      "Checked 2026-07-02: WordPress site reachable; /san-francisco-apartments/ renders building links and prices client-side only (no server-rendered listing data). Needs a JS-capable adapter or its data endpoint reverse-engineered.",
    notes: "SF/Oakland/LA property manager with significant SF inventory.",
    parserVersion: 0,
  },
  {
    id: "brick_and_timber",
    name: "Brick + Timber",
    sourceSystem: "property_manager_direct",
    adapterType: "none",
    priority: "normal",
    registryStatus: "disabled_needs_adapter",
    enabled: false,
    listingUrl: "https://rentbt.com/browse-apartments/",
    baseUrl: "https://rentbt.com",
    websiteUrl: "https://rentbt.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 1,
    maxPagesPerRun: 5,
    maxDetailPagesPerRun: 20,
    geocodeEnabled: true,
    needsJavaScript: null,
    hasPagination: null,
    requiresDetailPages: null,
    blocksAutomation: null,
    safeForPersonalLowFrequencyFetching: null,
    permissionStatus: "needs_review",
    sourceStatusNotes:
      "Checked 2026-07-02: brickandtimber.com redirects to rentbt.com (WordPress + RentCafe). /browse-apartments/ exists but renders listings client-side (0 listing links in static HTML); homepage exposes a few featured /listing/<id> links server-side. Listings CPT is not exposed via wp-json. Needs a JS-capable adapter or RentCafe API work.",
    notes: "Boutique SF property manager with real per-listing pages at rentbt.com/listing/<id>.",
    parserVersion: 0,
  },
  {
    id: "lapham_company",
    name: "Lapham Company",
    sourceSystem: "property_manager_direct",
    adapterType: "none",
    priority: "normal",
    registryStatus: "disabled_blocked_or_not_practical",
    enabled: false,
    listingUrl: null,
    baseUrl: null,
    websiteUrl: "https://www.laphamcompany.com",
    region: "San Francisco / East Bay",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 1,
    maxPagesPerRun: 5,
    maxDetailPagesPerRun: 20,
    geocodeEnabled: true,
    needsJavaScript: null,
    hasPagination: null,
    requiresDetailPages: null,
    blocksAutomation: null,
    safeForPersonalLowFrequencyFetching: null,
    permissionStatus: "needs_review",
    sourceStatusNotes:
      "Checked 2026-07-02: site reachable and /for-rent/ listing links ARE server-rendered — but current inventory is Oakland/Berkeley/Danville (East Bay), not San Francisco. Not practical for an SF-focused tool; revisit only if they list SF units.",
    notes: "Older Bay Area property management firm; inventory verified East Bay as of 2026-07-02.",
    parserVersion: 0,
  },
  {
    id: "ballast_investments",
    name: "Ballast Investments buildings",
    sourceSystem: "property_manager_direct",
    adapterType: "none",
    priority: "normal",
    registryStatus: "disabled_needs_review",
    enabled: false,
    listingUrl: null,
    baseUrl: null,
    websiteUrl: null,
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 1,
    maxPagesPerRun: 5,
    maxDetailPagesPerRun: 20,
    geocodeEnabled: true,
    needsJavaScript: null,
    hasPagination: null,
    requiresDetailPages: null,
    blocksAutomation: null,
    safeForPersonalLowFrequencyFetching: null,
    permissionStatus: "needs_review",
    sourceStatusNotes:
      "No public listing page identified yet; building-specific availability pages may be discoverable later.",
    notes: "Placeholder for building-specific pages.",
    parserVersion: 0,
  },
];
