import type { NewSourceRow } from "@/db/schema";

/**
 * SF source registry seed data. `npm run seed:sources` upserts these.
 *
 * Operational notes (robots/permission fields) were recorded from manual
 * checks on 2026-07-01 and are refreshed automatically at run time. They are
 * operational bookkeeping for a personal low-frequency tool — not legal
 * conclusions.
 *
 * Only sources with a registered adapterType ("craigslist", "rentsfnow",
 * "rentbt", "mosser") can actually run; everything else is seeded disabled for
 * future investigation so the registry documents the roadmap.
 */

type SourceSeed = Omit<NewSourceRow, "createdAt" | "updatedAt">;

export const SOURCE_SEEDS: SourceSeed[] = [
  {
    id: "craigslist_sf",
    name: "Craigslist SF apartments",
    sourceSystem: "craigslist",
    adapterType: "craigslist",
    priority: "critical",
    registryStatus: "enabled_working",
    enabled: true,
    listingUrl: "https://sfbay.craigslist.org/search/sfc/apa",
    baseUrl: "https://sfbay.craigslist.org",
    websiteUrl: "https://sfbay.craigslist.org",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 2500,
    timeoutMs: 25000,
    retryCount: 2,
    maxPagesPerRun: 1,
    // The static search page serves ~360 newest SF postings, and EVERY bit of
    // rich data (photos, beds/baths, address, description) lives only on the
    // detail page — a listing that misses this budget is saved at "card depth"
    // with nothing but a title, price, and rough location. At 50, a busy day's
    // 130+ new postings couldn't all be fetched, and the un-fetched ones were
    // starved on later runs (newer postings always outrank them), so they were
    // stuck info-less forever. 300 comfortably covers a normal night plus a
    // backlog while staying under the page size; detail is still only fetched
    // for new/changed listings, so a quiet night fetches far fewer.
    maxDetailPagesPerRun: 300,
    geocodeEnabled: true,
    needsJavaScript: false,
    hasPagination: false,
    requiresDetailPages: true,
    blocksAutomation: false,
    safeForPersonalLowFrequencyFetching: true,
    permissionStatus: "ok_personal_low_frequency",
    sourceStatusNotes:
      "Verified 2026-07-01: robots.txt disallows only /reply, /fb/, /suggest, /flag, /mf, /mailflag, /eaf — search and posting pages are not disallowed. Static search fallback serves ~360 newest results without JavaScript; offset pagination is ignored by the static page (JS-only), so each run sees the freshest ~360 SF postings. Detail pages are classic server-rendered HTML with coordinates, attributes, and photos.",
    notes:
      "Freshest small-landlord inventory in SF, but the noisiest: needs scam/duplicate handling. Fetch cautiously — daily or manual, never aggressive. Detail pages fetched only for new/changed postings.",
    parserVersion: 1,
  },
  {
    id: "rentsfnow",
    name: "RentSFNow",
    sourceSystem: "rentsfnow",
    adapterType: "rentsfnow",
    priority: "high",
    registryStatus: "enabled_working",
    enabled: true,
    listingUrl: "https://www.rentsfnow.com/search/",
    baseUrl: "https://www.rentsfnow.com",
    websiteUrl: "https://www.rentsfnow.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 2000,
    timeoutMs: 25000,
    retryCount: 2,
    maxPagesPerRun: 10,
    maxDetailPagesPerRun: 40,
    geocodeEnabled: true,
    needsJavaScript: false,
    hasPagination: true,
    requiresDetailPages: true,
    blocksAutomation: false,
    safeForPersonalLowFrequencyFetching: true,
    permissionStatus: "ok_personal_low_frequency",
    sourceStatusNotes:
      "Verified 2026-07-01: WordPress site; its own search UI POSTs to /wp-admin/admin-ajax.php (action=wpas_ajax_load) and receives server-rendered result HTML with explicit current_page/last_page markers and building-level map coordinates. Unit detail pages are server-rendered. Also lists Oakland/LA inventory — adapter filters to San Francisco.",
    notes:
      "Property-manager direct inventory (large SF portfolio). Structured, well-paginated, and polite to fetch at low frequency.",
    parserVersion: 1,
  },
  {
    id: "zillow_sf",
    name: "Zillow SF rentals",
    sourceSystem: "zillow_manual_or_reference",
    adapterType: "none",
    priority: "reference_only",
    registryStatus: "disabled_reference_only",
    enabled: false,
    listingUrl: "https://www.zillow.com/san-francisco-ca/rentals/",
    baseUrl: "https://www.zillow.com",
    websiteUrl: "https://www.zillow.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 0,
    requestDelayMs: 5000,
    timeoutMs: 25000,
    retryCount: 0,
    maxPagesPerRun: 0,
    maxDetailPagesPerRun: 0,
    geocodeEnabled: false,
    needsJavaScript: true,
    hasPagination: true,
    requiresDetailPages: true,
    blocksAutomation: true,
    safeForPersonalLowFrequencyFetching: false,
    permissionStatus: "reference_only_do_not_fetch",
    sourceStatusNotes:
      "Reference only in phase one. Heavy JS app with strong anti-automation; not an appropriate foundation for a polite personal scraper. Use manually in a browser for cross-checking.",
    notes: "Seeded disabled by design. Revisit only with a clearly acceptable integration path.",
    parserVersion: 0,
  },
  {
    id: "apartments_com_sf",
    name: "Apartments.com SF rentals",
    sourceSystem: "apartments_manual_or_reference",
    adapterType: "none",
    priority: "reference_only",
    registryStatus: "disabled_reference_only",
    enabled: false,
    listingUrl: "https://www.apartments.com/san-francisco-ca/",
    baseUrl: "https://www.apartments.com",
    websiteUrl: "https://www.apartments.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 0,
    requestDelayMs: 5000,
    timeoutMs: 25000,
    retryCount: 0,
    maxPagesPerRun: 0,
    maxDetailPagesPerRun: 0,
    geocodeEnabled: false,
    needsJavaScript: true,
    hasPagination: true,
    requiresDetailPages: true,
    blocksAutomation: true,
    safeForPersonalLowFrequencyFetching: false,
    permissionStatus: "reference_only_do_not_fetch",
    sourceStatusNotes:
      "Reference only in phase one. Large marketplace with anti-automation; use manually in a browser for cross-checking.",
    notes: "Seeded disabled by design.",
    parserVersion: 0,
  },
  {
    id: "structure_properties",
    name: "Structure Properties",
    sourceSystem: "property_manager_direct",
    adapterType: "appfolio_js",
    priority: "normal",
    registryStatus: "disabled_needs_adapter",
    enabled: false,
    listingUrl: "https://structureproperties.appfolio.com/listings",
    baseUrl: "https://structureproperties.appfolio.com",
    websiteUrl: "https://www.structureproperties.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 1,
    maxPagesPerRun: 5,
    maxDetailPagesPerRun: 20,
    geocodeEnabled: true,
    needsJavaScript: true,
    hasPagination: true,
    requiresDetailPages: true,
    blocksAutomation: null,
    safeForPersonalLowFrequencyFetching: null,
    permissionStatus: "needs_review",
    sourceStatusNotes:
      "Rendered with Playwright 2026-07-02: classic AppFolio 'snowfolio' widget (#result_container) confirmed, but currently shows 'We currently have no available properties for rent' — zero inventory. A parser can't be verified against an empty page, so the appfolio_js adapter is deferred until this (or another classic-widget SF AppFolio PM) has live units. The Playwright rendering infrastructure is now in place, so writing it is straightforward once inventory appears.",
    notes: "SF property manager on AppFolio (classic snowfolio widget). Currently empty. One appfolio_js adapter would cover every classic-widget AppFolio PM.",
    parserVersion: 0,
  },
  {
    id: "gaetani_real_estate",
    name: "Gaetani Real Estate",
    sourceSystem: "property_manager_direct",
    adapterType: "appfolio_js",
    priority: "normal",
    registryStatus: "disabled_needs_adapter",
    enabled: false,
    listingUrl: "https://gaetani.appfolio.com/listings",
    baseUrl: "https://gaetani.appfolio.com",
    websiteUrl: "https://www.gaetanirealestate.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 1,
    maxPagesPerRun: 5,
    maxDetailPagesPerRun: 20,
    geocodeEnabled: true,
    needsJavaScript: true,
    hasPagination: true,
    requiresDetailPages: true,
    blocksAutomation: null,
    safeForPersonalLowFrequencyFetching: null,
    permissionStatus: "needs_review",
    sourceStatusNotes:
      "Rendered with Playwright 2026-07-02: uses AppFolio's newer 'v2' UI (not the classic snowfolio #result_container that Structure uses) and currently shows no listings/prices. Needs a separate v2 parser AND live inventory before an adapter is worthwhile.",
    notes: "Long-standing SF property manager on AppFolio (v2 UI). Currently empty; different markup from Structure.",
    parserVersion: 0,
  },
  {
    id: "trinity_sf",
    name: "Trinity SF",
    sourceSystem: "property_manager_direct",
    adapterType: "none",
    priority: "normal",
    registryStatus: "disabled_needs_review",
    enabled: false,
    listingUrl: "https://www.trinitysf.com",
    baseUrl: "https://www.trinitysf.com",
    websiteUrl: "https://www.trinitysf.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 1,
    maxPagesPerRun: 5,
    maxDetailPagesPerRun: 20,
    geocodeEnabled: true,
    needsJavaScript: null,
    hasPagination: null,
    requiresDetailPages: null,
    blocksAutomation: null,
    safeForPersonalLowFrequencyFetching: null,
    permissionStatus: "needs_review",
    sourceStatusNotes:
      "Re-investigated 2026-07-02 (incl. Playwright render): homepage and neighborhood pages (russian-hill-apartments, soma-apartments, trinitysf-apartments) load, but NONE expose availability or pricing — even fully rendered they show zero prices and no listing/unit data or JSON feed, only a hy.ly chat widget. Trinity's live availability appears to live in a separate leasing system not reachable from the public site. No adapter is feasible until that source is identified. Left disabled.",
    notes: "Large SF landlord (thousands of units), but public site exposes no machine-readable availability. Revisit if a listings feed is found.",
    parserVersion: 0,
  },
  {
    id: "mosser_living",
    name: "Mosser Living",
    sourceSystem: "property_manager_direct",
    adapterType: "mosser",
    priority: "high",
    registryStatus: "enabled_working",
    enabled: true,
    listingUrl: "https://www.mosserliving.com/san-francisco-apartments/",
    baseUrl: "https://www.mosserliving.com",
    websiteUrl: "https://www.mosserliving.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 1500,
    timeoutMs: 25000,
    retryCount: 2,
    maxPagesPerRun: 1,
    maxDetailPagesPerRun: 80,
    geocodeEnabled: false,
    needsJavaScript: false,
    hasPagination: false,
    requiresDetailPages: true,
    blocksAutomation: false,
    safeForPersonalLowFrequencyFetching: true,
    permissionStatus: "ok_personal_low_frequency",
    sourceStatusNotes:
      "Verified 2026-07-02: RentPress-powered WordPress site. The SF property list comes from wp-json (wp/v2/rentpress_property filtered by the 'San Francisco' city term, ~60 properties), and each property page embeds a complete `data-floorplans` JSON blob in its raw HTML (bedrooms, baths, rent, sqft, availability, exact coordinates, city, neighborhood, amenities, pet policy, photos, application URL). The adapter reads those directly over plain HTTP — no browser. Listings are at floorplan granularity (each available floorplan = one listing); the feed spans SF/Oakland/LA and the adapter filters to San Francisco.",
    notes: "Large SF property manager (~60 SF buildings). Floorplan-level listings via RentPress embedded data. Fetches the SF property pages each run (capped by maxDetailPagesPerRun); complete set so missing-listing tracking runs safely.",
    parserVersion: 1,
  },
  {
    id: "brick_and_timber",
    name: "Brick + Timber",
    sourceSystem: "property_manager_direct",
    adapterType: "rentbt",
    priority: "normal",
    registryStatus: "enabled_working",
    enabled: true,
    listingUrl: "https://rentbt.com/browse-apartments/",
    baseUrl: "https://rentbt.com",
    websiteUrl: "https://rentbt.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 2,
    maxPagesPerRun: 1,
    maxDetailPagesPerRun: 0,
    geocodeEnabled: false,
    needsJavaScript: false,
    hasPagination: false,
    requiresDetailPages: false,
    blocksAutomation: false,
    safeForPersonalLowFrequencyFetching: true,
    permissionStatus: "ok_personal_low_frequency",
    sourceStatusNotes:
      "Verified 2026-07-02: brickandtimber.com redirects to rentbt.com. The browse page is a JS-rendered WordPress + RentCafe app, but it is backed by a clean public REST endpoint (/wp-json/property-search/v1/data/) that returns every available unit as structured JSON in ONE request — price, beds/baths/sqft, unit, building address, EXACT coordinates, neighborhood, amenities, concessions, full photo gallery, and application URL. The adapter uses that directly (no browser, no pagination, no detail pages), which is more polite and reliable than rendering. The feed includes East Bay (Berkeley) units; the adapter filters to San Francisco by building city.",
    notes: "Boutique SF property manager. Uses the site's own JSON feed (no scraping/rendering). Single complete response, so missing-listing tracking runs safely; coordinates are exact so no geocoding is needed.",
    parserVersion: 1,
  },
  {
    id: "dahlia_sf",
    name: "DAHLIA — SF affordable housing",
    sourceSystem: "direct_html",
    adapterType: "dahlia",
    priority: "high",
    registryStatus: "enabled_working",
    enabled: true,
    listingUrl: "https://housing.sfgov.org/listings/for-rent",
    baseUrl: "https://housing.sfgov.org",
    websiteUrl: "https://housing.sfgov.org",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 1500,
    timeoutMs: 25000,
    retryCount: 2,
    maxPagesPerRun: 1,
    maxDetailPagesPerRun: 0,
    geocodeEnabled: true,
    needsJavaScript: false,
    hasPagination: false,
    requiresDetailPages: false,
    blocksAutomation: false,
    safeForPersonalLowFrequencyFetching: true,
    permissionStatus: "ok_personal_low_frequency",
    sourceStatusNotes:
      "Verified 2026-07-03: the City & County of San Francisco's official affordable-housing portal exposes a public JSON API (/api/v1/listings?type=rental) that returns every open rental listing in one response — building address + zip, per-bedroom-type unit summaries (min/max rent, sqft, availability), income limits, status, and a building photo. The adapter reads it directly (no browser, no pagination, no detail pages) and splits each building into one listing per unit type. No coordinates in the feed, so addresses are geocoded. robots.txt allows all but /wp-admin-style paths (none used).",
    notes:
      "Below-market-rate / income-restricted (BMR + tax-credit lottery) homes. A legitimate, official, complete SF feed — every unit type per building, one polite request. Descriptions flag the income limits and lottery process; the DAHLIA page is the source of truth for eligibility and applying.",
    parserVersion: 1,
  },
  {
    id: "rentalsinsf",
    name: "Rentals in SF",
    sourceSystem: "direct_html",
    adapterType: "rentalsinsf",
    priority: "normal",
    registryStatus: "enabled_working",
    enabled: true,
    listingUrl: "https://www.rentalsinsf.com/current-listings/",
    baseUrl: "https://www.rentalsinsf.com",
    websiteUrl: "https://www.rentalsinsf.com",
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 2,
    maxPagesPerRun: 1,
    maxDetailPagesPerRun: 20,
    geocodeEnabled: true,
    needsJavaScript: false,
    hasPagination: false,
    requiresDetailPages: true,
    blocksAutomation: false,
    safeForPersonalLowFrequencyFetching: true,
    permissionStatus: "ok_personal_low_frequency",
    sourceStatusNotes:
      "Verified 2026-07-03: a long-running SF rental brokerage on WordPress. The public `rental` custom post type (/wp-json/wp/v2/rental?per_page=100&_embed) returns every current listing with title (street address), permalink, full description HTML, amenity taxonomy, and an embedded featured photo — in one request. Price / beds / baths live in the prose, extracted best-effort (null when not stated); addresses are geocoded. robots.txt allows all but /wp-admin (Crawl-delay: 10).",
    notes:
      "Smaller boutique inventory (~14 listings) but real SF units with photos (so vision runs). Structured fields are partial by nature — the original listing is the source of truth.",
    parserVersion: 1,
  },
  {
    id: "lapham_company",
    name: "Lapham Company",
    sourceSystem: "property_manager_direct",
    adapterType: "none",
    priority: "normal",
    registryStatus: "disabled_blocked_or_not_practical",
    enabled: false,
    listingUrl: null,
    baseUrl: null,
    websiteUrl: "https://www.laphamcompany.com",
    region: "San Francisco / East Bay",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 1,
    maxPagesPerRun: 5,
    maxDetailPagesPerRun: 20,
    geocodeEnabled: true,
    needsJavaScript: null,
    hasPagination: null,
    requiresDetailPages: null,
    blocksAutomation: null,
    safeForPersonalLowFrequencyFetching: null,
    permissionStatus: "needs_review",
    sourceStatusNotes:
      "Checked 2026-07-02: site reachable and /for-rent/ listing links ARE server-rendered — but current inventory is Oakland/Berkeley/Danville (East Bay), not San Francisco. Not practical for an SF-focused tool; revisit only if they list SF units.",
    notes: "Older Bay Area property management firm; inventory verified East Bay as of 2026-07-02.",
    parserVersion: 0,
  },
  {
    id: "ballast_investments",
    name: "Ballast Investments buildings",
    sourceSystem: "property_manager_direct",
    adapterType: "none",
    priority: "normal",
    registryStatus: "disabled_needs_review",
    enabled: false,
    listingUrl: null,
    baseUrl: null,
    websiteUrl: null,
    region: "San Francisco",
    city: "San Francisco",
    state: "CA",
    crawlIntervalHours: 24,
    requestDelayMs: 3000,
    timeoutMs: 25000,
    retryCount: 1,
    maxPagesPerRun: 5,
    maxDetailPagesPerRun: 20,
    geocodeEnabled: true,
    needsJavaScript: null,
    hasPagination: null,
    requiresDetailPages: null,
    blocksAutomation: null,
    safeForPersonalLowFrequencyFetching: null,
    permissionStatus: "needs_review",
    sourceStatusNotes:
      "No public listing page identified yet; building-specific availability pages may be discoverable later.",
    notes: "Placeholder for building-specific pages.",
    parserVersion: 0,
  },
];
